# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='due_date',
            field=models.DateField(),
        ),
    ]
